#!/usr/bin/env php
<?php

require_once __DIR__.'/BlogKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$kernel = new BlogKernel('dev', false);

$application = new Application($kernel);
$application->run();
